In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [4]:
# numpy를 이용하여 1차원 배열로 변형하기

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
# 배열의 크기 확인
arr1.shape

(5,)

In [6]:
# 2차원 List
data2 = [
          [1, 2, 3, 4],
          [5, 6, 7, 8]
        ]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [7]:
# numpy를 2차원 배열로 변형하기
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.shape

(2, 4)

In [9]:
# 0으로 구성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros([3,5,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
# 1로만 구성된 배열 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
# 뒤의 값으로 된 배열 만들기
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [17]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# 숫자 8로 구성된 3행 5열 생성
np.full([3,5], 8)
# print(np.ones([3,5])*8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [24]:
# 범위가 있는 배열 생성
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
arr1.dtype

dtype('float64')

In [27]:
arr3 = np.array([1,2,3,4,5], dtype=np.int64)
arr3.dtype

dtype('int64')

In [28]:
# data type을 변경
float_arr1 = arr3.astype(np.float64)
float_arr1.dtype

dtype('float64')

In [29]:
float_arr1

array([1., 2., 3., 4., 5.])

In [32]:
# 연산
arr1 = np.array([[1,2,3], [4,5,6]], dtype=np.float64)
arr2 = np.array([[7,8,9], [10,11,12]], dtype=np.float64)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [33]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [34]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [35]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [36]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [37]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [38]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [39]:
arr3 = 1 / arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[5]

5

In [42]:
arr[5:9]

array([5, 6, 7, 8])

In [43]:
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [45]:
arr[:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[8:]

array([12,  9])

### 2차원 배열


In [47]:
arr2d =np.array([[1,2,3,4], [5,6,7,8,], [9,10,11,12], [13,14,15,16]])

In [48]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
arr2d.dtype

dtype('int64')

In [53]:
# 2번행의 자료 출력
arr2d[2,:]

array([ 9, 10, 11, 12])

In [55]:
# 1에서 2번행의 자료 출력
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
# 3번열의 자료 출력
arr2d[:,3]

array([ 4,  8, 12, 16])

In [57]:
# 0, 1열의 자료 출력
arr2d[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [58]:
# 1행 2열의 자료 출력
arr2d[1,2]

7

In [59]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
arr2d[0:2,1:3] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
# 난수 발생
- rand : 0부터 1사이의 균일 분포
- randn : 가우시안 표준 정규 분포
- randint : 균일 분포의 정수 난수

### Boolean Indexing

In [65]:
names = np.array(["Charles", "Kenny", "Hayoung", "Charles", "Hayoung", "Kenny", "Kenny"])
data = np.random.randn(7, 4)

In [66]:
names

array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny',
       'Kenny'], dtype='<U7')

In [67]:
names.shape

(7,)

In [73]:
data

array([[-0.28930985,  1.18800019, -0.28223071, -0.85239762],
       [-0.125658  , -0.1974609 , -0.84269143,  1.03762654],
       [-1.24769553,  1.06630609,  0.46409096, -0.20034106],
       [-0.6882434 , -0.49476454, -0.75483436, -0.20887431],
       [-0.65627729, -2.58733244,  0.14157379, -0.70395062],
       [ 1.97094086, -1.06171206,  0.20183723,  0.7733092 ],
       [-1.13513389, -0.39047647,  0.10493934,  0.44415418]])

In [69]:
data.shape

(7, 4)

In [71]:
# Mask를 이용한 추출
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [72]:
data[names == "Charles", :]

array([[-0.28930985,  1.18800019, -0.28223071, -0.85239762],
       [-0.6882434 , -0.49476454, -0.75483436, -0.20887431]])

In [74]:
data[(names == "Charles") | (names == "Kenny"), :]

array([[-0.28930985,  1.18800019, -0.28223071, -0.85239762],
       [-0.125658  , -0.1974609 , -0.84269143,  1.03762654],
       [-0.6882434 , -0.49476454, -0.75483436, -0.20887431],
       [ 1.97094086, -1.06171206,  0.20183723,  0.7733092 ],
       [-1.13513389, -0.39047647,  0.10493934,  0.44415418]])

In [75]:
data[:]

array([[-0.28930985,  1.18800019, -0.28223071, -0.85239762],
       [-0.125658  , -0.1974609 , -0.84269143,  1.03762654],
       [-1.24769553,  1.06630609,  0.46409096, -0.20034106],
       [-0.6882434 , -0.49476454, -0.75483436, -0.20887431],
       [-0.65627729, -2.58733244,  0.14157379, -0.70395062],
       [ 1.97094086, -1.06171206,  0.20183723,  0.7733092 ],
       [-1.13513389, -0.39047647,  0.10493934,  0.44415418]])

In [76]:
data[:, 3]

array([-0.85239762,  1.03762654, -0.20034106, -0.20887431, -0.70395062,
        0.7733092 ,  0.44415418])

In [78]:
# data의 4번째 열 값 중 0보다 작은 것의 mask 만들기

data[data[:, 3] < 0, :]

array([[-0.28930985,  1.18800019, -0.28223071, -0.85239762],
       [-1.24769553,  1.06630609,  0.46409096, -0.20034106],
       [-0.6882434 , -0.49476454, -0.75483436, -0.20887431],
       [-0.65627729, -2.58733244,  0.14157379, -0.70395062]])

In [81]:
# data의 4번째 열의 값이 0보다 작은 data들을 0으로 대체하기
data[data[:,3] < 0, :] = 0
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.125658  , -0.1974609 , -0.84269143,  1.03762654],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.97094086, -1.06171206,  0.20183723,  0.7733092 ],
       [-1.13513389, -0.39047647,  0.10493934,  0.44415418]])

In [82]:
# 정렬
arr = np.random.rand(8)
arr

array([0.41653431, 0.04556538, 0.034681  , 0.76236204, 0.93688077,
       0.59867544, 0.00994486, 0.42450773])

In [83]:
# 오름차순 정렬
np.sort(arr)

array([0.00994486, 0.034681  , 0.04556538, 0.41653431, 0.42450773,
       0.59867544, 0.76236204, 0.93688077])

In [85]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.93688077, 0.76236204, 0.59867544, 0.42450773, 0.41653431,
       0.04556538, 0.034681  , 0.00994486])

In [86]:
arr = np.random.rand(5,3)
arr

array([[0.44812893, 0.98176814, 0.14448188],
       [0.59292455, 0.73373368, 0.68381864],
       [0.66746969, 0.78883178, 0.4641504 ],
       [0.06437413, 0.06631713, 0.16303918],
       [0.36127872, 0.28981289, 0.75200524]])

In [88]:
np.sort(arr, axis=0) # 0 : 열 방향

array([[0.06437413, 0.06631713, 0.14448188],
       [0.36127872, 0.28981289, 0.16303918],
       [0.44812893, 0.73373368, 0.4641504 ],
       [0.59292455, 0.78883178, 0.68381864],
       [0.66746969, 0.98176814, 0.75200524]])

In [89]:
np.sort(arr, axis=1) # 1 : 행방향

array([[0.14448188, 0.44812893, 0.98176814],
       [0.59292455, 0.68381864, 0.73373368],
       [0.4641504 , 0.66746969, 0.78883178],
       [0.06437413, 0.06631713, 0.16303918],
       [0.28981289, 0.36127872, 0.75200524]])

In [91]:
np.sort(arr, axis=1)[:,::-1]

array([[0.98176814, 0.44812893, 0.14448188],
       [0.73373368, 0.68381864, 0.59292455],
       [0.78883178, 0.66746969, 0.4641504 ],
       [0.16303918, 0.06631713, 0.06437413],
       [0.75200524, 0.36127872, 0.28981289]])

In [92]:
# 중복제거
np.unique(names)

array(['Charles', 'Hayoung', 'Kenny'], dtype='<U7')

---
# reshape

In [93]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
arr.shape

(8,)

In [95]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
# 3차원 배열로 변경
arr2 = np.reshape(arr, (2,2,2))
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [103]:
# 2차원 배열을 1차원으로 변경
arr3 = arr1.reshape(-1)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [104]:
arr4 = arr2.reshape(-1, 1)
arr4

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [105]:
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])