In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../Data/gpascore.csv")
data.head()

admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

admit : 합격여부    
gre : 영어성적    
gpa : 학점    
rank : 지원한 대학원 수준    

### Preprocessing(전처리)

In [3]:
# 결측치 처리
data.isnull().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [4]:
# 결측치 데이터 삭제
data.dropna(inplace=True)

# 결측치 데이터를 다른 값으로 대체
# data.fillna(100)

In [5]:
data.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [6]:
# rank의 종류 파악
sorted(data["rank"].unique())

[1, 2, 3, 4]

In [7]:
# 영어 점수의 최소값과 최대값
print("최대값 :", data["gre"].max())
print("최소값 :", data["gre"].min())

최대값 : 800.0
최소값 : 220.0


In [8]:
# Training Data
x = data.drop("admit", axis=1)
x.head()

gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [9]:
# target Data
y = data["admit"]
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [10]:
x.count()

gre     425
gpa     425
rank    425
dtype: int64

> 입력층은 layer로 치지 않는다

---
### Deep Learning Model 만들기


In [11]:
from tensorflow import keras

In [12]:
input_layer = keras.layers.InputLayer(input_shape=(3,))
hidden_layer = keras.layers.Dense(256, activation="tanh")
output_layer = keras.layers.Dense(1, activation="sigmoid")

In [13]:
model = keras.Sequential(
  [
    input_layer,
    hidden_layer,
    output_layer
  ]
)

2022-07-20 10:53:50.229249: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [14]:
# 손실함수
model.compile(optimizer="adam", loss="binary_crossentropy", metrics="accuracy")
# Optimizer : learning rate를 알맞게 조정해줌
# - adam
# - adagrad
# - adadelta
# - rmsprop
# - sgd
# loss : 손실함수
# - binary_crossentropy : 분류 및 확률 예측
# metrics : 모델의 평가 기준

In [15]:
# 학습시키기
import numpy as np
model.fit(np.array(x), np.array(y), epochs=500)

Epoch 1/500
14/14 [==============================] - 0s 1ms/step - loss: 0.6914 - accuracy: 0.5365
Epoch 2/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6928 - accuracy: 0.5600
Epoch 3/500
14/14 [==============================] - 0s 2ms/step - loss: 0.7017 - accuracy: 0.5153
Epoch 4/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6824 - accuracy: 0.5929
Epoch 5/500
14/14 [==============================] - 0s 3ms/step - loss: 0.6782 - accuracy: 0.5694
Epoch 6/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6834 - accuracy: 0.5247
Epoch 7/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6708 - accuracy: 0.5741
Epoch 8/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6732 - accuracy: 0.5741
Epoch 9/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6645 - accuracy: 0.5812
Epoch 10/500
14/14 [==============================] - 0s 2ms/step - loss: 0.6733 - accuracy: 0.5671
Epoch 11/

In [16]:
# hidden layer의 가중치 값 출력
hidden_layer.get_weights()[0]

array([[-1.07164785e-01, -1.50074037e-02,  1.47170305e-01,
        -1.22011498e-01, -3.50041799e-02, -5.62662855e-02,
         3.60484868e-02, -4.54110950e-02, -5.18092215e-02,
         4.32270914e-02, -2.38187518e-02, -1.17165640e-01,
        -8.81718472e-02, -6.42171130e-02, -1.21388935e-01,
        -1.31274536e-01, -5.22959158e-02,  6.30940646e-02,
         1.18232161e-01,  6.83971941e-02, -2.04669554e-02,
         2.15492323e-02,  8.45074654e-02, -5.49980476e-02,
        -4.37098294e-02, -9.63024795e-02, -3.95429656e-02,
        -1.56928841e-02, -5.36731631e-02,  9.31242108e-02,
        -9.89416540e-02, -2.17040125e-02, -3.57634835e-02,
        -3.54075059e-02,  5.44692874e-02,  3.87860686e-02,
         1.46758288e-01, -5.32072634e-02,  2.14054268e-02,
         6.12077266e-02, -1.18691958e-01, -4.08615693e-02,
        -9.11489278e-02, -6.43083751e-02,  1.18303616e-02,
         1.24266773e-01, -1.10645078e-01, -4.39880863e-02,
        -4.25569937e-02, -9.23784822e-02,  1.35409944e-0

In [17]:
# hidden layer의 출력 확인하기
intermediate_layer_model = keras.Model(inputs=model.input, outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(np.array(x))

In [18]:
intermediate_output

<tf.Tensor: shape=(425, 256), dtype=float32, numpy=
array([[-1.        , -0.9999943 ,  1.        , ..., -1.        ,
         1.        , -1.        ],
       [-1.        , -1.        ,  1.        , ..., -1.        ,
         1.        , -1.        ],
       [-1.        , -1.        ,  1.        , ..., -1.        ,
         1.        , -1.        ],
       ...,
       [-1.        , -0.99999946,  1.        , ..., -1.        ,
         1.        , -1.        ],
       [-1.        , -1.        ,  1.        , ..., -1.        ,
         1.        , -1.        ],
       [-1.        , -1.        ,  1.        , ..., -1.        ,
         1.        , -1.        ]], dtype=float32)>